### ISSUE TITLE
spawn deck should allow 0 precision

### ISSUE THREAD

**Issue by backpacker69** [PeerAssets/chizukeki#15]
not all decks require non integer divisions

**Comment by peerchemist** [comment]
This is critical, please fix asap.

**Comment by micimize** [comment]
This should be fixed by 9dc1af6 - if successful [dcf7a9b39a01dabcefdd9b148cc08b2e2586858dee4561d5aa32c6f2242cf1f3](https://explorer.peercoin.net:8000/tx/dcf7a9b39a01dabcefdd9b148cc08b2e2586858dee4561d5aa32c6f2242cf1f3) should be a 0 precision deck. Waiting for papi syncing to [test again](https://papi.peercoin.net/restless/v1/cards?q={%22filters%22:[{%22name%22:%22txid%22,%22op%22:%22like%22,%22val%22:%22dcf7a9b39a01dabcefdd9b148cc08b2e2586858dee4561d5aa32c6f2242cf1f3%%22}]})

**Comment by peerchemist** [comment]
![screenshot from 2018-06-05 20-32-10](https://user-images.githubusercontent.com/7818961/40995555-a0771314-68ff-11e8-92be-05c833ee0579.png)
Works.
